### ISSUE TITLE
OpenAI \ Exceptions \ ErrorException - unclear, please help

### ISSUE THREAD

**Issue by nezaboravi** [openai-php/laravel#47] opened 2023-06-01 07:11 UTC
I am attaching image of screen.
Error is unclear, and i am not sure where to look at all

![image](https://github.com/openai-php/laravel/assets/1515172/f097ace1-7abb-475b-a017-8b81917d069c)

Pest test works:
![carbon(1)](https://github.com/openai-php/laravel/assets/1515172/1d2daa02-bf10-4272-8aa8-70ebb042d720)

**Comment by gehrisandro** [comment] 2023-06-07 16:24
This has been fixed in the latest version: 0.5.3

**Comment by makerstorage** [comment] 2023-06-14 15:32
Same here. Please check still exist in version: 0.5.3

**Comment by gehrisandro** [comment] 2023-06-14 19:17
I've tried various things, but I am not able to reproduce the issue.

@nezaboravi @kmilo2622 @Obacm @makerstorage Was anyone of you able to debug an find out, what the API actually returns or do you have a stable way to reproduce the issue?

**Comment by gehrisandro** [comment] 2023-06-14 19:59
Probably I run into the same issue right now:

For some error the API returns an error with an empty message, which leads to some confusion. If you are taking a closer look to the error exception details, the reason is visible, but this some kind of unexpected.

Exception Output:
![Screenshot 2023-06-14 at 21 52 28](https://github.com/openai-php/laravel/assets/25097194/632d8aa3-d9ab-4b58-8b0e-431daedbd9af)

Raw JSON error from the API:
![Screenshot 2023-06-14 at 21 54 14](https://github.com/openai-php/laravel/assets/25097194/7dfef735-0ec9-4579-a5e7-7e9800bcd8b4)

Maybe would could add some logic, like "if the message is empty copy the error code to the message". \
What do you think?

At least for the invalid API Key this doesn't look to bad:
![Screenshot 2023-06-14 at 21 58 49](https://github.com/openai-php/laravel/assets/25097194/0b5966d3-b5db-4f5d-bd74-2d9f6a03bfd6)

**Comment by nezaboravi** [comment] 2023-06-15 16:29
Problem here lays in env variable naming. 
min openai is actually two similar things, one is called display name and other is called id. In env file in laravel mislead me kind of so I wrote Coding Wisely as organisation name, and when I removed it and changed to organisation id provided in openai, it worked. Maybe just update environment name to be clear that that is ID

**Closed** 2023-06-23 20:08 UTC
